FROM golang:latest

WORKDIR /app

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy the files we need from our local project to the work directory (WORKDIR)
COPY . .

# Download our go packages
RUN go mod download

# See the .air.toml file's build bin and cmd properties for the specific cmds

# Expose ports to the outside world
EXPOSE 8080
EXPOSE 3001

CMD ["air", "-c", ".air.toml"]