global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: goginair 
    metrics_path: /metrics
    static_configs:
      - targets:
        - goginair:8080